# Generated by Django 5.1.2 on 2024-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
